# Copyright Drycc Community.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.47.0
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    tags:
      - drycc-common
    version: ~1.1.2
description: Prometheus is an open source monitoring and alerting system. It enables sysadmins to monitor their infrastructures by collecting metrics from configured targets at given intervals.
home: https://github.com/prometheus/prometheus
icon: https://drycc.com/assets/stacks/prometheus/img/prometheus-stack-220x234.png
keywords:
  - prometheus
  - monitoring
maintainers:
  - name: Drycc
    url: https://github.com/drycc/charts
name: prometheus
sources:
  - https://github.com/drycc/containers/tree/main/drycc/prometheus
  - https://github.com/prometheus/prometheus
  - https://github.com/prometheus-community/helm-charts
version: 0.2.3
