credential:
  {{- if (eq .Values.service.type "LoadBalancer") }}
  - name: host
    valueFrom:
      serviceRef:
        name: {{ printf "%s" (include "common.names.fullname" .) }}
        jsonpath: '{ .status.loadBalancer.ingress[*].ip }'
  - name: database
    valueFrom:
      secretKeyRef:
        name: {{ template "common.names.fullname" . }}-svcbind-custom-user
        jsonpath: '{ .data.database }' 
  - name: password
    valueFrom:
      secretKeyRef:
        name: {{ template "common.names.fullname" . }}-svcbind-custom-user
        jsonpath: '{ .data.username }' 
  - name: username
    valueFrom:
      secretKeyRef:
        name: {{ template "common.names.fullname" . }}-svcbind-custom-user
        jsonpath: '{ .data.username }' 
  - name: portrw
    valueFrom:
      secretKeyRef:
        name: {{ template "common.names.fullname" . }}-svcbind-custom-user
        jsonpath: '{ .data.portrw }' 
  - name: portro
    valueFrom:
      secretKeyRef:
        name: {{ template "common.names.fullname" . }}-svcbind-custom-user
        jsonpath: '{ .data.portro }' 
  {{- end }}

