fullnameOverride: hb-postgresql-standard-512

## PostgreSQL data Persistent Volume Storage Class
## If defined, storageClassName: <storageClass>
## If set to "-", storageClassName: "", which disables dynamic provisioning
## If undefined (the default) or set to null, no storageClassName spec is
##   set, choosing the default provisioner.  (gp2 on AWS, standard on
##   GKE, AWS & OpenStack)
##
primary:
  ## PostgreSQL Primary persistence configuration
  ##
  persistence:
    ## @param primary.persistence.enabled Enable PostgreSQL Primary data persistence using PVC
    ##
    enabled: true
     ## @param primary.persistence.size PVC Storage Request for PostgreSQL volume
    ##
    size: 512Gi

  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 400m
      memory: 8Gi

readReplicas:
  ## @param readReplicas.replicaCount Number of PostgreSQL read only replicas
  ##
  replicaCount: 1
  persistence:
    ## @param readReplicas.persistence.enabled Enable PostgreSQL read only data persistence using PVC
    ##
    enabled: true
    ## @param readReplicas.persistence.size PVC Storage Request for PostgreSQL volume
    ##
    size: 512Gi

  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 400m
      memory: 8Gi

## Maximum connections for the created user
postgresqlDbUserConnectionLimit: 512
