# Copyright Drycc Community.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: WorkFlow
  licenses: Apache-2.0
apiVersion: v2
appVersion: "2.8.0"
dependencies:
- name: common
  repository: oci://registry.drycc.cc/charts
  version: ~1.1.3
description: Apache Airflow is a tool to express and execute workflows as directed acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress and handle task dependencies.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- name: Drycc Community.
  url: https://github.com/bitnami/charts
name: airflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/airflow
version: 16.1.7
