## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: hb-airflow-standard-24c64g7w

## @section Airflow web parameters

web:
  ## @param web.replicaCount Number of Airflow web replicas
  ##
  replicaCount: 1
  ## Airflow web resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param web.resources.limits The resources limits for the Airflow web containers
  ## @param web.resources.requests The requested resources for the Airflow web containers
  ##
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi

## @section Airflow scheduler parameters

scheduler:
  ## @param scheduler.replicaCount Number of scheduler replicas
  ##
  replicaCount: 1
  ## Airflow scheduler resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param scheduler.resources.limits The resources limits for the Airflow scheduler containers
  ## @param scheduler.resources.requests The requested resources for the Airflow scheduler containers
  ##
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi

## @section Airflow worker parameters

worker:
  ## @param worker.replicaCount Number of Airflow worker replicas
  ##
  replicaCount: 7
  ## Airflow worker resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param worker.resources.limits The resources limits for the Airflow worker containers
  ## @param worker.resources.requests The requested resources for the Airflow worker containers
  ##
  resources:
    limits:
      cpu: 24
      memory: 64Gi
    requests:
      cpu: 12
      memory: 32Gi
