apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}-repl
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "patroni.fullname" . }}
    role: replica
spec:
  type: ClusterIP
  selector:
    app: {{ template "patroni.fullname" . }}
    cluster-name: {{ template "patroni.fullname" . }}
    role: replica
  ports:
  - port: 5432
    targetPort: 5432