credential:
{{- if (eq .Values.server.service.type "LoadBalancer") }}
  - name: EXTRANET_HOST
    valueFrom:
      serviceRef: 
        name: {{ template "prometheus.server.fullname" . }}
        jsonpath: '{ .status.loadBalancer.ingress[*].ip }'
{{- end }}
  - name: HOST
    valueFrom:
      serviceRef:
        name: {{ template "prometheus.server.fullname" . }}
        jsonpath: '{ .spec.clusterIP }'
  - name: PORT
    valueFrom:
      serviceRef:
        name: {{ template "prometheus.server.fullname" . }}
        jsonpath: ' { .spec.ports[?(@.name=="http")].port }' 
  - name: USER
    value: {{ .Values.server.username }} 
  - name: PASSWORD
    value: {{ .Values.server.password }} 

