# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: etcd
      image: registry.drycc.cc/drycc-addons/etcd:3.6
    - name: base
      image: registry.drycc.cc/drycc/base:trixie
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 3.6.6
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.4
description: etcd is a distributed key-value store designed to securely store data
  across a cluster. etcd is widely used in production on account of its reliability,
  fault-tolerance and ease of use.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/etcd/img/etcd-stack-220x234.png
keywords:
- etcd
- cluster
- database
- cache
- key-value
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: etcd
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/etcd
version: 12.0.20
