## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: hb-clickhouse-cluster-standard-8c32g500

## MinIO&reg; containers' resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
## We usually recommend not to specify default resources and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments with little
## resources, such as Minikube. If you do want to specify resources, uncomment the following
## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
## @param resources.limits The resources limits for the MinIO&reg; container
## @param resources.requests The requested resources for the MinIO&reg; container
##
resources:
  limits:
    cpu: 8000m
    memory: 32Gi
  requests:
    cpu: 8000m
    memory: 32Gi

persistence:
  size: 500Gi