# Copyright Drycc Community.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: flink
      image: registry.drycc.cc/drycc-addons/flink:1.17
apiVersion: v2
appVersion: 1.17.2
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.3
description: Apache Flink is a framework and distributed processing engine for stateful computations over unbounded and bounded data streams.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/flink/img/flink-stack-220x234.png
keywords:
- flink
- stream-processing
- batch-processing
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: flink
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/flink
version: 0.5.3
