annotations:
  category: Database
apiVersion: v2
appVersion: 22.8.6
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    tags:
      - drycc-common
    version: ~1.1.2
description: ClickHouse is an open-source column-oriented OLAP database management system. Use it to boost your database performance while providing linear scalability and hardware efficiency.
home: https://clickhouse.com/
icon: https://drycc.com/assets/stacks/clickhouse/img/clickhouse-stack-220x234.png
keywords:
  - database
  - sharding
maintainers:
  - name: Drycc
    url: https://github.com/drycc/charts
name: clickhouse
sources:
  - https://github.com/drycc/containers/tree/main/drycc/clickhouse
  - https://github.com/ClickHouse/ClickHouse
version: 24.0
