name: grafana
version: "10"
id: fff5b6c7-ed85-429b-8265-493e40cc53c7
description: "grafana"
displayName: "grafana"
metadata:
  displayName: "grafana"
  provider:
    name: drycc
    supportURL: http://grafana.io/
  documentationURL: https://github.com/drycc-addons/
tags: grafana
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: false
allow_parameters:
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "grafana.nodeSelector"
  required: false
archive: false
