annotations:
  category: Database
apiVersion: v2
appVersion: "11"
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
description: MariaDB is an open source, community-developed SQL database server that is widely in use around the world due to its enterprise features, flexibility, and collaboration with leading tech firms.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/mariadb
icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - prometheus
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: mariadb
sources:
  - https://github.com/bitnami/bitnami-docker-mariadb
  - https://github.com/prometheus/mysqld_exporter
  - https://mariadb.org
version: 10.4.5
