master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""

filer:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""

volume:
  replicas: 4
  persistence:
    meta:
      enabled: true
      size: 1Gi
      storageClass: ""
    data:
      enabled: true
      size: 200Gi
      storageClass: ""
  compactionMBps: 50
