## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: hb-kvrocks-standard-16c32g1024

## @section Kvrocks; master configuration parameters
##

master:
  ## Kvrocks; master resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param master.resources.limits The resources limits for the Kvrocks; master containers
  ## @param master.resources.requests The requested resources for the Kvrocks; master containers
  ##
  resources:
    limits:
      cpu: 16
      memory: 32Gi
    requests:
      cpu: 8
      memory: 16Gi
  ## Persistence parameters
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param master.persistence.enabled Enable persistence on Kvrocks; master nodes using Persistent Volume Claims
    ##
    enabled: true
    ## @param master.persistence.path The path the volume will be mounted at on Kvrocks; master containers
    ## NOTE: Useful when using different Kvrocks; images
    ##
    path: /drycc/kvrocks/data
    ## @param master.persistence.storageClass Persistent Volume storage class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
    ##
    storageClass: ""
    ## @param master.persistence.accessModes Persistent Volume access modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param master.persistence.size Persistent Volume size
    ##
    size: 1Ti

## @section Kvrocks; replicas configuration parameters
##

replica:
  ## @param replica.replicaCount Number of Kvrocks; replicas to deploy
  ##
  replicaCount: 3

  ## Kvrocks; replicas resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param replica.resources.limits The resources limits for the Kvrocks; replicas containers
  ## @param replica.resources.requests The requested resources for the Kvrocks; replicas containers
  ##
  resources:
    limits:
      cpu: 16
      memory: 32Gi
    requests:
      cpu: 8
      memory: 16Gi
  ## Persistence Parameters
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param replica.persistence.enabled Enable persistence on Kvrocks; replicas nodes using Persistent Volume Claims
    ##
    enabled: true
    ## @param replica.persistence.path The path the volume will be mounted at on Kvrocks; replicas containers
    ## NOTE: Useful when using different Kvrocks; images
    ##
    path: /drycc/kvrocks/data
    ## @param replica.persistence.storageClass Persistent Volume storage class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
    ##
    storageClass: ""
    ## @param replica.persistence.accessModes Persistent Volume access modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param replica.persistence.size Persistent Volume size
    ##
    size: 1Ti

sentinel:
  ## Persistence parameters
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param sentinel.persistence.enabled Enable persistence on Kvrocks; sentinel nodes using Persistent Volume Claims (Experimental)
    ##
    enabled: true
    ## @param sentinel.persistence.storageClass Persistent Volume storage class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
    ##
    storageClass: ""
    ## @param sentinel.persistence.accessModes Persistent Volume access modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param sentinel.persistence.size Persistent Volume size
    ##
    size: 128Mi

  ## Kvrocks; Sentinel resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param sentinel.resources.limits The resources limits for the Kvrocks; Sentinel containers
  ## @param sentinel.resources.requests The requested resources for the Kvrocks; Sentinel containers
  ##
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

proxy:
  ## Kvrocks; Sentinel resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param proxy.resources.limits The resources limits for the Kvrocks; Sentinel containers
  ## @param proxy.resources.requests The requested resources for the Kvrocks; Sentinel containers
  ##
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi