annotations:
  category: Database
apiVersion: v2
appVersion: 8.0.30
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    tags:
      - drycc-common
    version: ~1.1.2
description: MySQL is a fast, reliable, scalable, and easy to use open source relational database system. Designed to handle mission-critical, heavy-load production applications.
engine: gotpl
home: https://github.com/drycc/charts/tree/master/drycc/mysql
icon: https://drycc.com/assets/stacks/mysql/img/mysql-stack-220x234.png
keywords:
  - mysql
  - database
  - sql
  - cluster
  - high availability
maintainers:
  - name: Drycc
    url: https://github.com/drycc/charts
name: mysql
sources:
  - https://github.com/drycc/containers/tree/main/drycc/mysql
  - https://mysql.com
version: 9.3.5
