annotations:
  category: monitor
apiVersion: v2
appVersion: 2.41.0
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    tags:
      - drycc-common
    version: ~1.1.2
description:  Percona Monitoring and Management an open source database monitoring, observability and management tool 
engine: gotpl
home: https://github.com/drycc/charts/tree/master/drycc/pmm
icon: https://drycc.com/assets/stacks/pmm/img/pmm-stack-220x234.png
keywords:
  - mysql
  - postgres
  - mongodb
  - monitor
maintainers:
  - name: Drycc
    url: https://github.com/drycc/charts
name: pmm
sources:
  - https://github.com/drycc/containers/tree/main/drycc/mysql
  - https://github.com/percona/pmm
version: 2.41.0

