{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ printf "%s-ingress" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if eq .Values.service.type "LoadBalancer" }}
    - {}
    {{- else }}
    - ports:
        # Allow client connections
        - port: {{ .Values.listeners.client.containerPort }}
        # Allow communication controller
        - port: {{ .Values.listeners.controller.containerPort }}
        # Allow communication inter-broker
        - port: {{ .Values.listeners.interbroker.containerPort }}
        # Allow communication external
        - port: {{ .Values.listeners.external.containerPort }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        {{- if or .Values.networkPolicy.allowCurrentNamespace .Values.networkPolicy.allowNamespaces }}
        {{- if .Values.networkPolicy.allowCurrentNamespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        {{- end }}
        {{- range $namespace := .Values.networkPolicy.allowNamespaces }}
        {{- if $namespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    # Allow External connection
    {{- if .Values.externalAccess.enabled }}
    - ports:
        - port: {{ .Values.listeners.external.containerPort }}
        - port: {{ .Values.externalAccess.controller.service.ports.external }}
    {{- if .Values.networkPolicy.externalAccess.from }}
      from: {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.externalAccess.from "context" $ ) | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.metrics.kafka.enabled }}
    # Allow prometheus scrapes
    - ports:
        - port: {{ .Values.metrics.kafka.containerPorts.metrics }}
    {{- end }}
    {{- end }}
{{- end }}
