annotations:
  category: Database
apiVersion: v2
appVersion: "16"
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
description: PostgreSQL (Postgres) is an open source object-relational database known for reliability and data integrity. ACID-compliant, it supports foreign keys, joins, views, triggers and stored procedures.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
  - postgresql
  - postgres
  - database
  - sql
  - replication
  - cluster
  - patroni
maintainers:
  - email: zhang.eamon@hotmail.com
    name: zhangeamon
name: postgresql
sources:
  - https://github.com/drycc-addons/
  - https://www.postgresql.org/
version: 16.4
