## @param fullnameOverride String to fully override etcd.fullname template
##
fullnameOverride: hb-etcd-standard-1c2g

## etcd containers' resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
## We usually recommend not to specify default resources and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments with little
## resources, such as Minikube. If you do want to specify resources, uncomment the following
## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
## @param resources.limits The resources limits for etcd containers
## @param resources.requests The requested resources for etcd containers
##
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi

## @param replicaCount Number of etcd replicas to deploy
##
replicaCount: 3

## @section Persistence parameters
##

persistence:
  ## @param persistence.enabled Enable etcd data persistence using PVC
  ##
  enabled: true
  ## @param persistence.storageClass PVC Storage Class for etcd data volume
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.accessModes PVC Access Modes for etcd data volume
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size PVC Storage Request for etcd data volume
  ## If you change this value, you might have to adjust `etcd.diskFreeLimit` as well
  ##
  size: 5Gi
